# Generated by Django 4.2 on 2023-04-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_image_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_url',
        ),
    ]
