# Generated by Django 4.2 on 2023-04-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classification',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='confidence',
            field=models.IntegerField(null=True),
        ),
    ]
